// quiz actions
export const ALL_QUIZ_QUESTION_GET = 'ALL_QUIZ_QUESTION_GET';
export const ALL_QUIZ_QUESTION_GET_SUCCESS = 'ALL_QUIZ_QUESTION_GET_SUCCESS';
export const ALL_QUIZ_QUESTION_GET_FAILED = 'ALL_QUIZ_QUESTION_GET_FAILED';